resolution:
  width: 1920
  height: 1080
adb:
  host: 127.0.0.1
  port: 5555
  connect_timeout_s: 5
  dry_run: false
  serial: 127.0.0.1:5555
ocr:
  enabled: true
  lang: en
  elixir_roi: [0.4, 0.92, 0.6, 0.98]
  gold_roi: [0.85, 0.02, 0.95, 0.08]
  daily_wins_roi: [0.65, 0.02, 0.78, 0.08]
vision:
  save_unknown_crops: true
  crops_dir: data/crops
  enable_yolo: true
  yolo_model: yolo11n.pt
  yolo_conf_thresh: 0.35
  yolo_imgsz: 320
  battle_roi: [0.4, 0.85, 0.6, 0.92]
  cards_centers:
    - [0.2, 0.92]
    - [0.4, 0.92]
    - [0.6, 0.92]
    - [0.8, 0.92]
  safe_zone_roi: [0.1, 0.55, 0.9, 0.75]
  rewards_roi_center: [0.3, 0.4, 0.7, 0.6]
  rewards_roi_bottom: [0.4, 0.85, 0.6, 0.92]
  upgrade_roi: [0.45, 0.55, 0.55, 0.65]
rl:
  learning_rate: 3.0e-4
  gamma: 0.99
  n_steps: 2048
  batch_size: 64
  ent_coef: 0.01
  vf_coef: 0.5
  gae_lambda: 0.95
  clip_range: 0.2
logging:
  level: INFO
  file: logs/run.log
  max_bytes: 1048576
  backup_count: 3
ai:
  openai_api_key: ""  # Set your OpenAI API key here
  model: "gpt-4o"  # GPT-4 Vision model
  max_tokens: 1000
  temperature: 0.3
  analysis_interval: 2.0  # Seconds between AI analysis
  enable_narration: true  # Enable streamer-like commentary
  vision_detail: "low"  # low/high for cost control
